import { Box, Center, Text } from '@chakra-ui/react'
import { type NextPage } from 'next'
import Head from 'next/head'
import Navigation from '../components/Navigation'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box w={'100vw'} h={'100vh'}>
          <Navigation />
          <Center h={'100vh'}>
            <Text fontSize={'2xl'}>T3 Jobs</Text>
          </Center>
        </Box>
      </main>
    </>
  )
}

export default Home
